id = "activitywatch"
name = "activitywatch"
description = "ActivityWatch watcher support"
version = "0.1.2"
schema_version = 1
authors = ["Sacha Korban <z@sachk.com>"]
repository = "https://github.com/sachk/aw-watcher-zed"

[language_servers.activitywatch]
name = "activitywatch"
languages = [
  "AsciiDoc",
  "Astro",
  "Bash",
  "Biome",
  "Blade",
  "C",
  "C++",
  "Clojure",
  "CSharp",
  "CSS",
  "CSV",
  "D",
  "Dart",
  "Elixir",
  "Elm",
  "Erlang",
  "Fish",
  "FSharp",
  "GDScript",
  "Gleam",
  "Go",
  "GraphQL",
  "Haskell",
  "HEEX",
  "HTML",
  "Hy",
  "Idris",
  "Java",
  "JavaScript",
  "JSON",
  "JSONC",
  "Julia",
  "Kotlin",
  "Lua",
  "Markdown",
  "Nim",
  "Nix",
  "OCaml",
  "PHP",
  "PureScript",
  "Python",
  "Racket",
  "Roc",
  "Ruby",
  "Rust",
  "Scheme",
  "SCSS",
  "Shell Script",
  "SQL",
  "Swift",
  "TOML",
  "TSX",
  "TypeScript",
  "Vue.js",
  "WIT",
  "XML",
  "YAML",
  "Zig",
]
